<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $categoryIds = Category::pluck('id', 'name');
        $brandIds = Brand::pluck('id', 'name');

        $products = [
            // ==================== CLOTHING (20) ====================
            [
                'category' => 'Clothing',
                'brand' => 'Levi\'s',
                'name' => '501 Original Fit Jeans',
                'price' => 89.99,
                'compare_price' => 119.99,
                'image' => 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&auto=format&fit=crop&q=80',
                'description' => 'The original blue jean since 1873. Straight fit with the signature button fly.',
                'featured' => true,
            ],
            [
                'category' => 'Clothing',
                'brand' => 'Levi\'s',
                'name' => 'Denim Trucker Jacket',
                'price' => 98.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=600&auto=format&fit=crop&q=80',
                'description' => 'The original jean jacket silhouette since 1967. Levi\'s denim truckers are built to last.',
                'featured' => false,
            ],
            [
                'category' => 'Clothing',
                'brand' => 'Levi\'s',
                'name' => 'Sherpa Lined Jacket',
                'price' => 128.00,
                'compare_price' => 148.00,
                'image' => 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop&q=80',
                'description' => 'Cozy sherpa lining adds warmth to the classic denim jacket design.',
                'featured' => true,
            ],
            [
                'category' => 'Clothing',
                'brand' => 'Levi\'s',
                'name' => 'Graphic Logo Tee',
                'price' => 29.99,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop&q=80',
                'description' => 'Soft combed cotton t-shirt featuring the iconic Levi\'s housemark logo.',
                'featured' => false,
            ],
            [
                'category' => 'Clothing',
                'brand' => 'Zara',
                'name' => 'Oversized Wool Coat',
                'price' => 189.00,
                'compare_price' => 249.00,
                'image' => 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&auto=format&fit=crop&q=80',
                'description' => 'Double-breasted long coat in a premium wool blend. Lapel collar and front pockets.',
                'featured' => true,
            ],
            [
                'category' => 'Clothing',
                'brand' => 'Zara',
                'name' => 'Slim Fit Poplin Shirt',
                'price' => 39.90,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&auto=format&fit=crop&q=80',
                'description' => 'Clean cotton poplin shirt with a sharp spread collar and barrel cuffs.',
                'featured' => false,
            ],
            [
                'category' => 'Clothing',
                'brand' => 'Zara',
                'name' => 'Linen Bomber Jacket',
                'price' => 79.90,
                'compare_price' => 99.90,
                'image' => 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop&q=80',
                'description' => 'Lightweight, breathable linen blend bomber jacket with ribbed trim details.',
                'featured' => false,
            ],
            [
                'category' => 'Clothing',
                'brand' => 'Zara',
                'name' => 'Faux Leather Jacket',
                'price' => 99.90,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop&q=80',
                'description' => 'Stylish biker jacket with lapels, metal zippers, and adjustable waist belt.',
                'featured' => false,
            ],
            [
                'category' => 'Clothing',
                'brand' => 'Nike',
                'name' => 'Dri-FIT Training Shirt',
                'price' => 35.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop&q=80',
                'description' => 'Athletic fit tee engineered with sweat-wicking Dri-FIT fabric to keep you cool.',
                'featured' => false,
            ],
            [
                'category' => 'Clothing',
                'brand' => 'Nike',
                'name' => 'Club Fleece Hoodie',
                'price' => 65.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&auto=format&fit=crop&q=80',
                'description' => 'Classic pullover style hoodie crafted from brushed-back fleece for premium warmth.',
                'featured' => true,
            ],
            [
                'category' => 'Clothing',
                'brand' => 'Nike',
                'name' => 'Windrunner Windbreaker',
                'price' => 100.00,
                'compare_price' => 120.00,
                'image' => 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&auto=format&fit=crop&q=80',
                'description' => 'Features the iconic 26-degree chevron design. Water-repellent and packable.',
                'featured' => false,
            ],
            [
                'category' => 'Clothing',
                'brand' => 'Nike',
                'name' => 'Pro Training Shorts',
                'price' => 40.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&auto=format&fit=crop&q=80',
                'description' => 'Stretchy, compressive support shorts designed for training and workout runs.',
                'featured' => false,
            ],
            [
                'category' => 'Clothing',
                'brand' => 'Adidas',
                'name' => 'Essentials Track Jacket',
                'price' => 75.00,
                'compare_price' => 90.00,
                'image' => 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&auto=format&fit=crop&q=80',
                'description' => 'Sporty full-zip jacket featuring the classic 3-stripes down the sleeves.',
                'featured' => true,
            ],
            [
                'category' => 'Clothing',
                'brand' => 'Adidas',
                'name' => 'Tiro Track Pants',
                'price' => 55.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1479064555552-3ef4979f8908?w=600&auto=format&fit=crop&q=80',
                'description' => 'Slim fit soccer track pants with ankle zips and moisture-absorbing AEROREADY.',
                'featured' => false,
            ],
            [
                'category' => 'Clothing',
                'brand' => 'Adidas',
                'name' => '3-Stripes Trefoil Tee',
                'price' => 35.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop&q=80',
                'description' => 'Retro lifestyle cotton t-shirt with signature stripes and Trefoil chest print.',
                'featured' => false,
            ],
            [
                'category' => 'Clothing',
                'brand' => 'Adidas',
                'name' => 'Originals Trefoil Hoodie',
                'price' => 70.00,
                'compare_price' => 85.00,
                'image' => 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&auto=format&fit=crop&q=80',
                'description' => 'Heavy French terry pullover with a bold kangaroo pocket and center branding.',
                'featured' => false,
            ],
            [
                'category' => 'Clothing',
                'brand' => 'Zara',
                'name' => 'Textured Knit Sweater',
                'price' => 49.90,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&auto=format&fit=crop&q=80',
                'description' => 'Stylish crewneck knit sweater with soft texture and comfortable ribbed cuffs.',
                'featured' => false,
            ],
            [
                'category' => 'Clothing',
                'brand' => 'Levi\'s',
                'name' => 'Slim Fit Chino Pants',
                'price' => 69.50,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1479064555552-3ef4979f8908?w=600&auto=format&fit=crop&q=80',
                'description' => 'Versatile flat-front stretch twill chinos. Perfect for dressing up or down.',
                'featured' => false,
            ],
            [
                'category' => 'Clothing',
                'brand' => 'Nike',
                'name' => 'Tech Fleece Joggers',
                'price' => 110.00,
                'compare_price' => 130.00,
                'image' => 'https://images.unsplash.com/photo-1479064555552-3ef4979f8908?w=600&auto=format&fit=crop&q=80',
                'description' => 'Lightweight warmth with a premium tapered fit and sleek side zipper pocket.',
                'featured' => true,
            ],
            [
                'category' => 'Clothing',
                'brand' => 'Adidas',
                'name' => 'Club Golf Polo Shirt',
                'price' => 45.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop&q=80',
                'description' => 'Breathable, moisture-wicking pique polo shirt engineered for active comfort.',
                'featured' => false,
            ],

            // ==================== SHOES (20) ====================
            [
                'category' => 'Shoes',
                'brand' => 'Nike',
                'name' => 'Air Max 270 Sneakers',
                'price' => 160.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
                'description' => 'Features Nike\'s tallest Air unit yet for super-soft heel cushioning.',
                'featured' => true,
            ],
            [
                'category' => 'Shoes',
                'brand' => 'Nike',
                'name' => 'Air Force 1 \'07',
                'price' => 115.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&auto=format&fit=crop&q=80',
                'description' => 'The hoops original. Premium white leather with durable stitched overlays.',
                'featured' => true,
            ],
            [
                'category' => 'Shoes',
                'brand' => 'Nike',
                'name' => 'Air Zoom Pegasus 40',
                'price' => 130.00,
                'compare_price' => 150.00,
                'image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
                'description' => 'Springy road running shoes with double Zoom Air units for fast energy return.',
                'featured' => false,
            ],
            [
                'category' => 'Shoes',
                'brand' => 'Nike',
                'name' => 'Blazer Mid \'77 Vintage',
                'price' => 105.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
                'description' => 'Retro high-top style with premium leather and synthetic overlays.',
                'featured' => false,
            ],
            [
                'category' => 'Shoes',
                'brand' => 'Adidas',
                'name' => 'Ultraboost Light',
                'price' => 190.00,
                'compare_price' => 220.00,
                'image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
                'description' => 'Experience epic energy with our lightest Ultraboost cushioning yet.',
                'featured' => true,
            ],
            [
                'category' => 'Shoes',
                'brand' => 'Adidas',
                'name' => 'Samba OG Shoes',
                'price' => 100.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&auto=format&fit=crop&q=80',
                'description' => 'Born on the pitch. The iconic Samba is a timeless indoor soccer silhouette.',
                'featured' => true,
            ],
            [
                'category' => 'Shoes',
                'brand' => 'Adidas',
                'name' => 'Stan Smith Crepe',
                'price' => 110.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&auto=format&fit=crop&q=80',
                'description' => 'Clean tennis court shoes updated with comfortable crepe crepe outsole.',
                'featured' => false,
            ],
            [
                'category' => 'Shoes',
                'brand' => 'Adidas',
                'name' => 'NMD_R1 Shoes',
                'price' => 150.00,
                'compare_price' => 180.00,
                'image' => 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&auto=format&fit=crop&q=80',
                'description' => 'Dynamic knit sneakers with signature EVA plugs in the Boost midsole.',
                'featured' => false,
            ],
            [
                'category' => 'Shoes',
                'brand' => 'Zara',
                'name' => 'Leather Chelsea Boots',
                'price' => 119.00,
                'compare_price' => 149.00,
                'image' => 'https://images.unsplash.com/photo-1638247025967-b4e38f6893b8?w=600&auto=format&fit=crop&q=80',
                'description' => 'Grained leather Chelsea boots with elastic side panels and pull tabs.',
                'featured' => true,
            ],
            [
                'category' => 'Shoes',
                'brand' => 'Zara',
                'name' => 'Minimalist White Sneakers',
                'price' => 59.90,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&auto=format&fit=crop&q=80',
                'description' => 'Clean design monochrome white casual sneakers with memory foam insoles.',
                'featured' => false,
            ],
            [
                'category' => 'Shoes',
                'brand' => 'Zara',
                'name' => 'Double Strap Sandals',
                'price' => 49.90,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&auto=format&fit=crop&q=80',
                'description' => 'Casual slip-on slides with adjustable buckle straps and molded cork footbed.',
                'featured' => false,
            ],
            [
                'category' => 'Shoes',
                'brand' => 'Zara',
                'name' => 'Suede Penny Loafers',
                'price' => 89.90,
                'compare_price' => 109.90,
                'image' => 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=600&auto=format&fit=crop&q=80',
                'description' => 'Classic slip-on luxury loafers in soft genuine suede leather.',
                'featured' => false,
            ],
            [
                'category' => 'Shoes',
                'brand' => 'Nike',
                'name' => 'React Infinity 3',
                'price' => 160.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
                'description' => 'Features high-density React foam and supportive design to guide your gait.',
                'featured' => false,
            ],
            [
                'category' => 'Shoes',
                'brand' => 'Adidas',
                'name' => 'Superstar Shoes',
                'price' => 100.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&auto=format&fit=crop&q=80',
                'description' => 'The original basketball shoe with the world-famous rubber shell toe.',
                'featured' => false,
            ],
            [
                'category' => 'Shoes',
                'brand' => 'Zara',
                'name' => 'Leather Derby Shoes',
                'price' => 99.90,
                'compare_price' => 129.90,
                'image' => 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=600&auto=format&fit=crop&q=80',
                'description' => 'Smart dress shoes in polished grain leather with a blind eyelet lace system.',
                'featured' => false,
            ],
            [
                'category' => 'Shoes',
                'brand' => 'Nike',
                'name' => 'ZoomX Vaporfly Next% 3',
                'price' => 260.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
                'description' => 'Elite racing shoe packed with ultra-springy ZoomX foam and a carbon fiber plate.',
                'featured' => true,
            ],
            [
                'category' => 'Shoes',
                'brand' => 'Adidas',
                'name' => 'Terrex Swift Hiking Shoes',
                'price' => 160.00,
                'compare_price' => 190.00,
                'image' => 'https://images.unsplash.com/photo-1582966772680-860e372bb558?w=600&auto=format&fit=crop&q=80',
                'description' => 'Lightweight trail hiking shoes with Continental rubber for outstanding grip.',
                'featured' => false,
            ],
            [
                'category' => 'Shoes',
                'brand' => 'Nike',
                'name' => 'Air Monarch IV Training',
                'price' => 75.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
                'description' => 'The classic dad sneaker featuring a thick supportive foam sole and full Air.',
                'featured' => false,
            ],
            [
                'category' => 'Shoes',
                'brand' => 'Adidas',
                'name' => 'Gazelle Originals',
                'price' => 100.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&auto=format&fit=crop&q=80',
                'description' => 'Low-profile court classic in premium pigskin suede with a gum rubber outsole.',
                'featured' => false,
            ],
            [
                'category' => 'Shoes',
                'brand' => 'Zara',
                'name' => 'High-Top Canvas Sneakers',
                'price' => 49.90,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&auto=format&fit=crop&q=80',
                'description' => 'Classic lace-up high-top casual sneakers in sturdy cotton canvas.',
                'featured' => false,
            ],

            // ==================== ACCESSORIES (20) ====================
            [
                'category' => 'Accessories',
                'brand' => 'Apple',
                'name' => 'Apple Watch Series 9 GPS',
                'price' => 399.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
                'description' => 'S9 SiP chip, double tap gesture control, bright Always-On Retina display.',
                'featured' => true,
            ],
            [
                'category' => 'Accessories',
                'brand' => 'Apple',
                'name' => 'Apple Watch Ultra 2',
                'price' => 799.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
                'description' => '49mm titanium case, ultimate rugged sports watch with dual-frequency GPS.',
                'featured' => true,
            ],
            [
                'category' => 'Accessories',
                'brand' => 'Nike',
                'name' => 'Heritage Backpack 25L',
                'price' => 45.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
                'description' => 'Spacious main compartment with internal sleeve and padded shoulder straps.',
                'featured' => false,
            ],
            [
                'category' => 'Accessories',
                'brand' => 'Nike',
                'name' => 'Polarized Sport Sunglasses',
                'price' => 98.00,
                'compare_price' => 120.00,
                'image' => 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop&q=80',
                'description' => 'Lightweight frames with wrap-around polarized lenses for maximum coverage.',
                'featured' => false,
            ],
            [
                'category' => 'Accessories',
                'brand' => 'Adidas',
                'name' => 'Classic Trefoil Backpack',
                'price' => 40.00,
                'compare_price' => 50.00,
                'image' => 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
                'description' => 'Retro school backpack with front zip pocket and printed contrast Trefoil.',
                'featured' => false,
            ],
            [
                'category' => 'Accessories',
                'brand' => 'Adidas',
                'name' => 'Superlite Performance Cap',
                'price' => 25.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?w=600&auto=format&fit=crop&q=80',
                'description' => 'Breathable, moisture-wicking training cap with built-in UV protection.',
                'featured' => false,
            ],
            [
                'category' => 'Accessories',
                'brand' => 'Levi\'s',
                'name' => 'Classic Leather Belt',
                'price' => 38.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1624222247344-550fb8ecf7db?w=600&auto=format&fit=crop&q=80',
                'description' => 'Crafted from thick full-grain harness leather. Brushed silver clamp buckle.',
                'featured' => false,
            ],
            [
                'category' => 'Accessories',
                'brand' => 'Levi\'s',
                'name' => 'Trifold Leather Wallet',
                'price' => 45.00,
                'compare_price' => 55.00,
                'image' => 'https://images.unsplash.com/photo-1627124224423-424a779ab6a7?w=600&auto=format&fit=crop&q=80',
                'description' => 'Slim genuine cowhide leather wallet equipped with RFID blocking shielding.',
                'featured' => false,
            ],
            [
                'category' => 'Accessories',
                'brand' => 'Zara',
                'name' => 'Canvas Duffle Travel Bag',
                'price' => 89.90,
                'compare_price' => 119.00,
                'image' => 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
                'description' => 'Heavyweight washed canvas weekend bag with adjustable shoulder strap.',
                'featured' => true,
            ],
            [
                'category' => 'Accessories',
                'brand' => 'Zara',
                'name' => 'Retro Round Sunglasses',
                'price' => 35.90,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop&q=80',
                'description' => 'Vintage design thin metal wire frames with dark impact-resistant lenses.',
                'featured' => false,
            ],
            [
                'category' => 'Accessories',
                'brand' => 'Zara',
                'name' => 'Saffiano Leather Wallet',
                'price' => 49.90,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1627124224423-424a779ab6a7?w=600&auto=format&fit=crop&q=80',
                'description' => 'Cross-hatch textured leather wallet with multiple card slots and zipper pocket.',
                'featured' => false,
            ],
            [
                'category' => 'Accessories',
                'brand' => 'Apple',
                'name' => 'Watch Sport Band 45mm',
                'price' => 49.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
                'description' => 'Durable fluoroelastomer athletic band with secure pin-and-tuck closure.',
                'featured' => false,
            ],
            [
                'category' => 'Accessories',
                'brand' => 'Nike',
                'name' => 'Club Unstructured Cap',
                'price' => 28.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?w=600&auto=format&fit=crop&q=80',
                'description' => 'Soft washed cotton twill dad cap featuring embroidered metal swoosh.',
                'featured' => false,
            ],
            [
                'category' => 'Accessories',
                'brand' => 'Adidas',
                'name' => 'Field Performance Gloves',
                'price' => 30.00,
                'compare_price' => 38.00,
                'image' => 'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?w=600&auto=format&fit=crop&q=80',
                'description' => 'Climawarm insulated running gloves with touchscreen compatible fingertips.',
                'featured' => false,
            ],
            [
                'category' => 'Accessories',
                'brand' => 'Levi\'s',
                'name' => 'Ribbed Cotton Beanie',
                'price' => 24.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?w=600&auto=format&fit=crop&q=80',
                'description' => 'Warm ribbed knit beanie featuring a stitched Levi\'s red tab logo.',
                'featured' => false,
            ],
            [
                'category' => 'Accessories',
                'brand' => 'Zara',
                'name' => 'Wide Brim Straw Fedora',
                'price' => 39.90,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?w=600&auto=format&fit=crop&q=80',
                'description' => 'Light woven straw fedora with an elegant black contrast ribbon trim.',
                'featured' => false,
            ],
            [
                'category' => 'Accessories',
                'brand' => 'Apple',
                'name' => 'MagSafe FineWoven Wallet',
                'price' => 59.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1627124224423-424a779ab6a7?w=600&auto=format&fit=crop&q=80',
                'description' => 'Made from durable microtwill, supports Find My tracking location.',
                'featured' => true,
            ],
            [
                'category' => 'Accessories',
                'brand' => 'Nike',
                'name' => 'Gym Drawstring Bag',
                'price' => 25.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
                'description' => 'Simple gym sack with drawstring cords doubling as shoulder straps.',
                'featured' => false,
            ],
            [
                'category' => 'Accessories',
                'brand' => 'Adidas',
                'name' => 'Reversible Webbed Belt',
                'price' => 30.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1624222247344-550fb8ecf7db?w=600&auto=format&fit=crop&q=80',
                'description' => 'Durable webbed strap belt with clamp buckle. Reverse side colors.',
                'featured' => false,
            ],
            [
                'category' => 'Accessories',
                'brand' => 'Zara',
                'name' => 'Silk Blend Patterned Scarf',
                'price' => 45.90,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?w=600&auto=format&fit=crop&q=80',
                'description' => 'Light, flowing silk blend scarf with a modern geometric pattern design.',
                'featured' => false,
            ],

            // ==================== ELECTRONICS (20) ====================
            [
                'category' => 'Electronics',
                'brand' => 'Apple',
                'name' => 'iPhone 15 Pro Max',
                'price' => 1199.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&fit=crop&q=80',
                'description' => 'Titanium design, powerful A17 Pro chip, advanced 5x Telephoto zoom camera.',
                'featured' => true,
            ],
            [
                'category' => 'Electronics',
                'brand' => 'Apple',
                'name' => 'MacBook Air M3 13"',
                'price' => 1099.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1496181130204-7552cc14b1e2?w=600&auto=format&fit=crop&q=80',
                'description' => 'Superlight and fast laptop powered by the next-generation Apple M3 chip.',
                'featured' => true,
            ],
            [
                'category' => 'Electronics',
                'brand' => 'Apple',
                'name' => 'iPad Air 11" M2',
                'price' => 599.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&auto=format&fit=crop&q=80',
                'description' => 'Liquid Retina display, M2 silicon performance, supports Apple Pencil Pro.',
                'featured' => false,
            ],
            [
                'category' => 'Electronics',
                'brand' => 'Apple',
                'name' => 'AirPods Pro 2 USB-C',
                'price' => 249.00,
                'compare_price' => 279.00,
                'image' => 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80',
                'description' => 'Rebuilt noise-cancelling earbuds, adaptive audio, spatial sound experience.',
                'featured' => true,
            ],
            [
                'category' => 'Electronics',
                'brand' => 'Sony',
                'name' => 'WH-1000XM5 Headphones',
                'price' => 398.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
                'description' => 'Industry-leading wireless noise-cancelling over-ear headphones.',
                'featured' => true,
            ],
            [
                'category' => 'Electronics',
                'brand' => 'Sony',
                'name' => 'PlayStation 5 Console',
                'price' => 499.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&auto=format&fit=crop&q=80',
                'description' => 'Lightning fast SSD loading, immersive 3D Audio and haptic controllers.',
                'featured' => true,
            ],
            [
                'category' => 'Electronics',
                'brand' => 'Sony',
                'name' => 'WF-1000XM5 ANC Earbuds',
                'price' => 299.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80',
                'description' => 'Real-time noise cancellation, high-resolution audio wireless sound quality.',
                'featured' => false,
            ],
            [
                'category' => 'Electronics',
                'brand' => 'Sony',
                'name' => 'SRS-XB100 Portable Speaker',
                'price' => 59.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&auto=format&fit=crop&q=80',
                'description' => 'Super compact Bluetooth outdoor speaker, waterproof and dustproof dust rating.',
                'featured' => false,
            ],
            [
                'category' => 'Electronics',
                'brand' => 'Samsung',
                'name' => 'Galaxy S24 Ultra',
                'price' => 1299.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&fit=crop&q=80',
                'description' => 'Titanium shell, 200MP camera, built-in S-Pen, and advanced Galaxy AI tools.',
                'featured' => true,
            ],
            [
                'category' => 'Electronics',
                'brand' => 'Samsung',
                'name' => '55" Neo QLED 4K TV',
                'price' => 999.00,
                'compare_price' => 1299.00,
                'image' => 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&auto=format&fit=crop&q=80',
                'description' => 'Ultra-fine light control with Quantum Mini LEDs. Immersive Dolby Atmos.',
                'featured' => false,
            ],
            [
                'category' => 'Electronics',
                'brand' => 'Samsung',
                'name' => 'Galaxy Buds2 Pro',
                'price' => 229.00,
                'compare_price' => 249.00,
                'image' => 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80',
                'description' => 'Ergonomic fit, 24-bit studio quality audio, intelligent active noise cancellation.',
                'featured' => false,
            ],
            [
                'category' => 'Electronics',
                'brand' => 'Samsung',
                'name' => 'Galaxy Tab S9 11"',
                'price' => 799.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&auto=format&fit=crop&q=80',
                'description' => 'Dynamic AMOLED 2X screen, IP68 water resistant tablet with high performance.',
                'featured' => false,
            ],
            [
                'category' => 'Electronics',
                'brand' => 'Dell',
                'name' => 'XPS 13 9340 Laptop',
                'price' => 999.00,
                'compare_price' => 1199.00,
                'image' => 'https://images.unsplash.com/photo-1496181130204-7552cc14b1e2?w=600&auto=format&fit=crop&q=80',
                'description' => 'Precision crafted aluminum chassis, Intel Core Ultra 7 processor, thin design.',
                'featured' => true,
            ],
            [
                'category' => 'Electronics',
                'brand' => 'Dell',
                'name' => 'UltraSharp 27" 4K Monitor',
                'price' => 479.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&auto=format&fit=crop&q=80',
                'description' => 'Exceptional color accuracy with IPS Black technology and 4K USB-C hub connectivity.',
                'featured' => true,
            ],
            [
                'category' => 'Electronics',
                'brand' => 'Dell',
                'name' => 'Inspiron Small Desktop',
                'price' => 499.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1496181130204-7552cc14b1e2?w=600&auto=format&fit=crop&q=80',
                'description' => 'Space saving compact desktop computer powered by latest Intel processors.',
                'featured' => false,
            ],
            [
                'category' => 'Electronics',
                'brand' => 'Dell',
                'name' => 'Premier Wireless Combo',
                'price' => 99.00,
                'compare_price' => 120.00,
                'image' => 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&auto=format&fit=crop&q=80',
                'description' => 'Multi-device RF and Bluetooth keyboard/mouse set. Long battery runtime.',
                'featured' => false,
            ],
            [
                'category' => 'Electronics',
                'brand' => 'Sony',
                'name' => 'PlayStation VR2 Headset',
                'price' => 549.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&auto=format&fit=crop&q=80',
                'description' => 'Stunning 4K HDR visuals and groundbreaking immersive tactile controllers.',
                'featured' => false,
            ],
            [
                'category' => 'Electronics',
                'brand' => 'Apple',
                'name' => 'Apple TV 4K 128GB',
                'price' => 149.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&auto=format&fit=crop&q=80',
                'description' => 'Cinematic streaming with A15 Bionic chip and intuitive Siri aluminum remote.',
                'featured' => false,
            ],
            [
                'category' => 'Electronics',
                'brand' => 'Samsung',
                'name' => 'Smart Monitor M8 32"',
                'price' => 399.00,
                'compare_price' => 499.00,
                'image' => 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&auto=format&fit=crop&q=80',
                'description' => 'Ultra-thin smart display with built-in streaming apps and magnetic camera.',
                'featured' => false,
            ],
            [
                'category' => 'Electronics',
                'brand' => 'Dell',
                'name' => 'Dual Charge Dock HD22',
                'price' => 189.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&auto=format&fit=crop&q=80',
                'description' => 'USB-C dual display docking station with integrated Qi wireless smartphone charger.',
                'featured' => false,
            ],

            // ==================== HOME & KITCHEN (20) ====================
            [
                'category' => 'Home & Kitchen',
                'brand' => 'Samsung',
                'name' => 'Bespoke Jet Stick Vacuum',
                'price' => 599.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80',
                'description' => 'Powerful cordless stick vacuum with self-emptying clean station tower.',
                'featured' => true,
            ],
            [
                'category' => 'Home & Kitchen',
                'brand' => 'Samsung',
                'name' => 'Bespoke Air Purifier',
                'price' => 349.00,
                'compare_price' => 429.00,
                'image' => 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&auto=format&fit=crop&q=80',
                'description' => '360 degree air intake purification with custom chic design panels.',
                'featured' => true,
            ],
            [
                'category' => 'Home & Kitchen',
                'brand' => 'Samsung',
                'name' => 'Smart Front Load Washer',
                'price' => 899.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80',
                'description' => 'AI Smart Dial remembers your cycles and optimizes detergent volume automatically.',
                'featured' => false,
            ],
            [
                'category' => 'Home & Kitchen',
                'brand' => 'Samsung',
                'name' => 'Jet Bot Robot Vacuum',
                'price' => 499.00,
                'compare_price' => 599.00,
                'image' => 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80',
                'description' => 'LiDAR sensor-driven robotic vacuum for precise smart home layout maps.',
                'featured' => false,
            ],
            [
                'category' => 'Home & Kitchen',
                'brand' => 'Nike',
                'name' => 'HyperFuel Water Bottle 24oz',
                'price' => 24.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop&q=80',
                'description' => 'Leakproof puff valve bottle with textured grip panels for quick hydration.',
                'featured' => false,
            ],
            [
                'category' => 'Home & Kitchen',
                'brand' => 'Adidas',
                'name' => 'Steel Thermal Flask 1L',
                'price' => 35.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop&q=80',
                'description' => 'Vacuum insulated double-walled steel keeps cold drinks chilled for 24 hours.',
                'featured' => false,
            ],
            [
                'category' => 'Home & Kitchen',
                'brand' => 'Zara',
                'name' => 'Home Ribbed Ceramic Vase',
                'price' => 29.90,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80',
                'description' => 'Elegant white ribbed ceramic flower vase with a textured matte finish.',
                'featured' => false,
            ],
            [
                'category' => 'Home & Kitchen',
                'brand' => 'Zara',
                'name' => 'Home Linen Tablecloth',
                'price' => 49.90,
                'compare_price' => 59.90,
                'image' => 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80',
                'description' => 'Pure European linen tablecloth, pre-washed for relaxed rustic texture.',
                'featured' => false,
            ],
            [
                'category' => 'Home & Kitchen',
                'brand' => 'Zara',
                'name' => 'Home Scented Wax Candle Set',
                'price' => 35.90,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&auto=format&fit=crop&q=80',
                'description' => 'Trio of long-burning soy wax candles infused with essential sandalwood oil.',
                'featured' => false,
            ],
            [
                'category' => 'Home & Kitchen',
                'brand' => 'Zara',
                'name' => 'Home Stoneware Plate Set',
                'price' => 69.90,
                'compare_price' => 89.90,
                'image' => 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
                'description' => 'Set of 4 handcrafted organic shape stoneware dessert plates with grey glaze.',
                'featured' => false,
            ],
            [
                'category' => 'Home & Kitchen',
                'brand' => 'Samsung',
                'name' => 'Smart Counter Refrigerator',
                'price' => 1999.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80',
                'description' => 'Features built-in Family Hub smart screen and interior cameras.',
                'featured' => true,
            ],
            [
                'category' => 'Home & Kitchen',
                'brand' => 'Samsung',
                'name' => 'Range Smart Microwave',
                'price' => 349.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80',
                'description' => 'Smart microwave with high extraction power ventilation hood built-in.',
                'featured' => false,
            ],
            [
                'category' => 'Home & Kitchen',
                'brand' => 'Zara',
                'name' => 'Home Linen Bedspread Set',
                'price' => 149.00,
                'compare_price' => 199.00,
                'image' => 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80',
                'description' => 'Soft, natural breathable linen bedspread with two matching pillow shams.',
                'featured' => false,
            ],
            [
                'category' => 'Home & Kitchen',
                'brand' => 'Zara',
                'name' => 'Home Velvet Cushion Cover',
                'price' => 25.90,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80',
                'description' => 'Plush cotton velvet decorative throw pillow cushion cover with zip closure.',
                'featured' => false,
            ],
            [
                'category' => 'Home & Kitchen',
                'brand' => 'Nike',
                'name' => 'Sport Quick Dry Towel',
                'price' => 29.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop&q=80',
                'description' => 'Super absorbent quick-dry microfiber towel. Comes with zip pouch.',
                'featured' => false,
            ],
            [
                'category' => 'Home & Kitchen',
                'brand' => 'Adidas',
                'name' => 'Camo Yoga Training Mat',
                'price' => 39.00,
                'compare_price' => 49.00,
                'image' => 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop&q=80',
                'description' => 'Cushioned non-slip 6mm thick mat designed for yoga, pilates and fitness workouts.',
                'featured' => false,
            ],
            [
                'category' => 'Home & Kitchen',
                'brand' => 'Zara',
                'name' => 'Home Rattan Storage Basket',
                'price' => 39.90,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80',
                'description' => 'Handcrafted rattan laundry and toy organization basket with integrated side handles.',
                'featured' => false,
            ],
            [
                'category' => 'Home & Kitchen',
                'brand' => 'Samsung',
                'name' => 'AirDresser Clothing Wardrobe',
                'price' => 1299.00,
                'compare_price' => 1599.00,
                'image' => 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80',
                'description' => 'Steam and sanitize system refreshes clothing to reduce odor and wrinkles.',
                'featured' => true,
            ],
            [
                'category' => 'Home & Kitchen',
                'brand' => 'Zara',
                'name' => 'Home Handcrafted Glass Carafe',
                'price' => 32.90,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
                'description' => 'Individually mouthblown glass water carafe topped with a solid oak wood stopper.',
                'featured' => false,
            ],
            [
                'category' => 'Home & Kitchen',
                'brand' => 'Samsung',
                'name' => 'Bespoke Smart Microwave',
                'price' => 229.00,
                'compare_price' => null,
                'image' => 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80',
                'description' => 'Glass touch controls, custom colors, smart sensor cook technology.',
                'featured' => false,
            ],
        ];

        foreach ($products as $data) {
            $slug = Str::slug($data['name']);
            $categoryId = $categoryIds[$data['category']] ?? null;
            $brandId = $brandIds[$data['brand']] ?? null;

            if (! $categoryId) {
                $this->command->error("Category not found: {$data['category']}");

                continue;
            }

            // Safety: Skip updating if the product was modified by the admin
            $existing = Product::withTrashed()->where('slug', $slug)->first();
            if ($existing && $existing->updated_at != $existing->created_at) {
                continue;
            }

            $product = Product::withTrashed()->updateOrCreate(
                ['slug' => $slug],
                [
                    'category_id' => $categoryId,
                    'brand_id' => $brandId,
                    'name' => $data['name'],
                    'description' => $data['description'],
                    'price' => $data['price'],
                    'compare_price' => $data['compare_price'],
                    'quantity' => rand(10, 100),
                    'image' => $data['image'],
                    'is_featured' => $data['featured'],
                ]
            );

            if ($product->trashed()) {
                $product->restore();
            }
        }

        $this->command->info('Created exactly '.count($products).' products.');
    }
}
